services:
  cl-assistant_postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cl-assistant
    ports:
      - "5432:5432"
    volumes:
      - cl-assistant_postgres:/var/lib/postgresql/data
volumes:
  ranking_copilot_postgres:
    driver: local
